{{- if and (not .Values.auth.existingSecret) (or .Values.auth.apiKeys .Values.auth.jwtSecret .Values.auth.workerToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "queueflow.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "queueflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.auth.apiKeys }}
  {{ $.Values.auth.existingSecretKeys.apiKeys }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.jwtSecret }}
  {{ $.Values.auth.existingSecretKeys.jwtSecret }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.workerToken }}
  {{ $.Values.auth.existingSecretKeys.workerToken }}: {{ . | quote }}
  {{- end }}
{{- end }}
