#!/usr/bin/env bash
#
# Regenerate the QueueFlow client SDKs from the OpenAPI spec.
#
# The spec is generated FROM the Rust code (`make spec`), so it can never drift
# from the running server. This script then drives openapi-generator to produce
# each language SDK. Generated files are canonical output — do not edit by hand.
#
# Requires: docker, and a generated spec at spec/openapi.json (run `make spec`).
#
# Each SDK is a GENERATED CORE plus a thin HAND-WRITTEN ergonomic facade. The
# facade (a QueueFlow client, wait_for_* pollers, a workflow builder) is what
# raw codegen cannot emit; it is injected at generation time as a supporting
# file from sdk-templates/<lang>/ (see sdk-configs/<lang>.yaml `files`).
#
# NOTE: Two SDKs are NOT generated by THIS script:
#   - TypeScript (../queueflow-sdk-nodejs) has the same generated-core + facade
#     split, but its core is regenerated from the SDK repo with
#     `npm run generate-core`; the facade lives in that repo's src/.
#     `scripts/check-ts-sdk.mjs` guards the core+facade against spec drift.
#   - Rust ships as the native `queueflow-client` crate in this workspace,
#     which reuses the engine's own domain types (no generation can beat that).
# Both are no-ops if requested explicitly.
#
# Usage:
#   scripts/generate-sdks.sh            # all generated SDKs (python, go)
#   scripts/generate-sdks.sh python     # one

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="${ROOT}/spec/openapi.json"
IMAGE="openapitools/openapi-generator-cli:v7.10.0"

# language -> sibling output directory (relative to the repo root's parent).
# A function (not an associative array) so this runs on the bash 3.2 that ships
# with macOS as well as bash 4+.
out_dir_for() {
  case "$1" in
    python)     echo "${ROOT}/../queueflow-sdk-python" ;;
    typescript) echo "${ROOT}/../queueflow-sdk-nodejs" ;;
    go)         echo "${ROOT}/../queueflow-sdk-go" ;;
    *)          echo "" ;;
  esac
}

if [[ ! -f "${SPEC}" ]]; then
  echo "spec not found: ${SPEC}" >&2
  echo "Run 'make spec' first." >&2
  exit 1
fi

generate() {
  local name="$1"

  # The TypeScript SDK is hand-written; never regenerate (and never wipe) it.
  if [[ "${name}" == "typescript" ]]; then
    echo "==> Skipping typescript: ../queueflow-sdk-nodejs is hand-written, not generated."
    return 0
  fi
  # The Rust SDK is the native queueflow-client crate in this workspace.
  if [[ "${name}" == "rust" ]]; then
    echo "==> Skipping rust: use the native crates/queueflow-client instead of a generated client."
    return 0
  fi

  local out
  out="$(out_dir_for "${name}")"
  local config="${ROOT}/sdk-configs/${name}.yaml"

  if [[ -z "${out}" ]]; then
    echo "unknown SDK target: ${name}" >&2
    exit 2
  fi
  if [[ ! -f "${config}" ]]; then
    echo "missing config: ${config}" >&2
    exit 2
  fi
  if [[ ! -d "${out}" ]]; then
    echo "SDK output directory missing: ${out}" >&2
    echo "Create it (e.g. 'git init \"${out}\"') before regenerating." >&2
    exit 1
  fi

  # Wipe everything except .git so stale generated files do not linger.
  find "${out}" -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +

  echo "==> Generating ${name} SDK into ${out}"
  # Mount the spec, config, and output dir individually so a generation can
  # never write outside its target. The per-language facade template dir is
  # mounted at /templates (referenced by the config's `templateDir` + `files`);
  # every other template falls back to the generator's built-in default.
  local tmpl="${ROOT}/sdk-templates/${name}"
  local tmpl_mount=()
  if [[ -d "${tmpl}" ]]; then
    tmpl_mount=(-v "${tmpl}:/templates:ro")
  fi
  docker run --rm \
    -v "${SPEC}:/spec/openapi.json:ro" \
    -v "${config}:/config.yaml:ro" \
    -v "${out}:/out" \
    "${tmpl_mount[@]}" \
    "${IMAGE}" generate \
      -i /spec/openapi.json \
      -c /config.yaml \
      -o /out
}

targets=("$@")
if [[ ${#targets[@]} -eq 0 || "${targets[0]}" == "all" ]]; then
  # typescript (hand-written) and rust (native crate) intentionally omitted.
  targets=(python go)
fi

for t in "${targets[@]}"; do
  generate "${t}"
done

echo "==> Done."
