#!/usr/bin/env bash
#
# Regenerate the QueueFlow client SDKs from the OpenAPI spec.
#
# The spec is generated FROM the Rust code (`make spec`), so it can never drift
# from the running server. This script then drives openapi-generator to produce
# each language SDK. Generated files are canonical output — do not edit by hand.
#
# Requires: docker, and a generated spec at spec/openapi.json (run `make spec`).
#
# Each SDK is a GENERATED CORE plus a thin HAND-WRITTEN ergonomic facade. The
# facade (a QueueFlow client, wait_for_* pollers, a workflow builder) is what
# raw codegen cannot emit; it is injected at generation time as a supporting
# file from sdk-templates/<lang>/ (see sdk-configs/<lang>.yaml `files`).
#
# NOTE: TypeScript (../queueflow-sdk-nodejs) is NOT generated by THIS script:
# it has the same generated-core + facade split, but its core is regenerated
# from the SDK repo with `npm run generate-core`; the facade lives in that
# repo's src/. `scripts/check-ts-sdk.mjs` guards the core+facade against spec
# drift. Requesting it here is a no-op.
#
# The native `queueflow-client` crate in this workspace remains the
# engine-adjacent Rust client (it reuses the engine's own domain types), but
# it depends on queueflow-core and so cannot be published standalone. The
# ../queueflow-sdk-rust repo carries the standalone generated crate, produced
# here like python/go.
#
# Usage:
#   scripts/generate-sdks.sh            # all generated SDKs (python, go, rust)
#   scripts/generate-sdks.sh python     # one

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="${ROOT}/spec/openapi.json"
IMAGE="openapitools/openapi-generator-cli:v7.10.0"

# language -> sibling output directory (relative to the repo root's parent).
# A function (not an associative array) so this runs on the bash 3.2 that ships
# with macOS as well as bash 4+.
out_dir_for() {
  case "$1" in
    python)     echo "${ROOT}/../queueflow-sdk-python" ;;
    typescript) echo "${ROOT}/../queueflow-sdk-nodejs" ;;
    go)         echo "${ROOT}/../queueflow-sdk-go" ;;
    rust)       echo "${ROOT}/../queueflow-sdk-rust" ;;
    *)          echo "" ;;
  esac
}

# Hand-written files live inside the generated repos, but the generator never
# emits them; without this list the pre-generation wipe would destroy them on
# every regen. They are restored BEFORE generation so the repo's
# .openapi-generator-ignore is in place and the generator leaves them alone
# (README.md, LICENSE, pyproject.toml and the CI workflows would otherwise be
# overwritten by the generator's stock templates). Paths may be directories.
handwritten_for() {
  local common="README.md LICENSE FACADE.md .openapi-generator-ignore .github"
  case "$1" in
    python) echo "${common} pyproject.toml test/test_facade.py test/test_live.py" ;;
    go)     echo "${common} facade_test.go live_test.go" ;;
    rust)   echo "${common} tests/facade.rs tests/live.rs" ;;
    *)      echo "" ;;
  esac
}

if [[ ! -f "${SPEC}" ]]; then
  echo "spec not found: ${SPEC}" >&2
  echo "Run 'make spec' first." >&2
  exit 1
fi

# The generation below WIPES each target repo before regenerating; a dead
# docker daemon after the wipe would leave the repo gutted. Fail here, before
# touching anything.
if ! docker info >/dev/null 2>&1; then
  echo "docker daemon is not reachable; refusing to wipe/regenerate SDK repos." >&2
  exit 1
fi

generate() {
  local name="$1"

  # The TypeScript SDK is hand-written; never regenerate (and never wipe) it.
  if [[ "${name}" == "typescript" ]]; then
    echo "==> Skipping typescript: ../queueflow-sdk-nodejs is hand-written, not generated."
    return 0
  fi

  local out
  out="$(out_dir_for "${name}")"
  local config="${ROOT}/sdk-configs/${name}.yaml"

  if [[ -z "${out}" ]]; then
    echo "unknown SDK target: ${name}" >&2
    exit 2
  fi
  if [[ ! -f "${config}" ]]; then
    echo "missing config: ${config}" >&2
    exit 2
  fi
  if [[ ! -d "${out}" ]]; then
    echo "SDK output directory missing: ${out}" >&2
    echo "Create it (e.g. 'git init \"${out}\"') before regenerating." >&2
    exit 1
  fi

  # Stash the hand-written files the wipe below would otherwise destroy.
  local keep tmp_keep
  tmp_keep="$(mktemp -d)"
  for keep in $(handwritten_for "${name}"); do
    if [[ -e "${out}/${keep}" ]]; then
      mkdir -p "${tmp_keep}/$(dirname "${keep}")"
      cp -R "${out}/${keep}" "${tmp_keep}/${keep}"
    fi
  done

  # Wipe everything except .git so stale generated files do not linger, then
  # put the hand-written files straight back so the generator sees the
  # .openapi-generator-ignore and skips everything it lists.
  find "${out}" -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
  for keep in $(handwritten_for "${name}"); do
    if [[ -e "${tmp_keep}/${keep}" ]]; then
      mkdir -p "${out}/$(dirname "${keep}")"
      cp -R "${tmp_keep}/${keep}" "${out}/${keep}"
    fi
  done
  rm -rf "${tmp_keep}"

  echo "==> Generating ${name} SDK into ${out}"
  # Mount the spec, config, and output dir individually so a generation can
  # never write outside its target. The per-language facade template dir is
  # mounted at /templates (referenced by the config's `templateDir` + `files`);
  # every other template falls back to the generator's built-in default.
  local tmpl="${ROOT}/sdk-templates/${name}"
  local tmpl_mount=()
  if [[ -d "${tmpl}" ]]; then
    tmpl_mount=(-v "${tmpl}:/templates:ro")
  fi
  docker run --rm \
    -v "${SPEC}:/spec/openapi.json:ro" \
    -v "${config}:/config.yaml:ro" \
    -v "${out}:/out" \
    "${tmpl_mount[@]}" \
    "${IMAGE}" generate \
      -i /spec/openapi.json \
      -c /config.yaml \
      -o /out

  # (Hand-written files were restored before generation; see above.)

  # The generator emits a go.mod with an empty require block, but the
  # generated test/ package imports testify; without a tidy the SDK ships
  # unable to compile its own tests.
  if [[ "${name}" == "go" ]]; then
    if command -v go >/dev/null 2>&1; then
      (cd "${out}" && go mod tidy)
    else
      echo "WARNING: go toolchain not found; run 'go mod tidy' in ${out} manually." >&2
    fi
  fi

  # pyproject.toml is hand-written (PEP 621, preserved above); the generator's
  # built-in setup.py still ships an openapitools contact address.
  if [[ "${name}" == "python" && -f "${out}/setup.py" ]]; then
    sed -i '' 's|team@openapitools.org|team@queueflow.dev|' "${out}/setup.py"
  fi
}

targets=("$@")
if [[ ${#targets[@]} -eq 0 || "${targets[0]}" == "all" ]]; then
  # typescript (hand-written) intentionally omitted.
  targets=(python go rust)
fi

for t in "${targets[@]}"; do
  generate "${t}"
done

echo "==> Done."
